# 메인 파일 이름을 지정하세요.
main_file = 'main.py' # fill here

# 데이타 파일들을 지정하세요.
data_files = [
    'animation_sheet.png', 'Scrallbackground.png', 'gate.png', 'heart.png',
    'LevelOfDifficulty.png', 'player.png', 'playersheet.png', 'redGate135.png',
    'star.png', 'title.png'
    # fill here
]

# 데이타가 들어있는 폴더들을 지정하세요.
data_folders = [
    # fill here
]

