# 메인 파일 이름을 지정하세요.
main_file = 'main.py' # fill here

# 데이타 파일들을 지정하세요.
data_files = [
    'applause.wav', 'bgm.mp3', 'boostsound.wav', 'ENCR10B.TTF', 'explanation.png',
    'finish_animation_sheet.png','finishline.png', 'fireparticle.png', 'gameclear.png',
    'gameover.png', 'heart.png', 'LevelOfDifficulty.png', 'minimap.png', 'minimap_arrow.png',
    'playersheet.png', 'point.png', 'redGate1.png', 'redGate135.png', 'ScrallbackgroundLong.png',
    'snowparticle.png', 'star.png', 'pointsound.wav', 'starsound.wav', 'title.png',
    'titlesound.mp3'
    # fill here
]

# 데이타가 들어있는 폴더들을 지정하세요.
data_folders = [
    # fill here
]

